"""Provenance recording and SHA-256 verification for O10 model assets.

Implements ADR-0007: the provenance manifest records the upstream repository,
the pinned commit and a per-file SHA-256 for every core runtime asset. Both CI
and load time verify hash and structure; tampering or a structure mismatch must
fail initialization (Spec testing decision 12).

The manifest is a plain mapping (JSON-serializable) so it can be authored by
hand, generated by a tooling step, or read from the install space. This module
does not depend on ROS; it operates on paths and bytes so it is unit-testable
without a sourced workspace.
"""

from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Union

from .contract import (
    SIDES,
    UPSTREAM_COMMIT,
    UPSTREAM_DECLARED_LICENSE,
    UPSTREAM_LICENSE_CONFIRMED,
    UPSTREAM_REPO,
)

# Core runtime assets per side (ADR-0007). Paths are relative to the asset root.
URDF_RELATIVE = "urdf/omnihand_{side}.urdf"
MJCF_RELATIVE = "mjcf/omnihand_{side}.xml"

MANIFEST_FILENAME = "provenance.json"

# Reference SHA-256 hashes of the pinned upstream core assets, computed from the
# exact bytes at UPSTREAM_COMMIT. These are the provenance target: when the
# upstream files are vendored (after license confirmation) the per-file hashes
# declared in the manifest MUST match these. They are NOT the asset bytes.
REFERENCE_HASHES: Dict[str, str] = {
    "urdf/omnihand_right.urdf": (
        "7a9150a3865eb40cb8434951efe63787da94c15c068ef81e157a252b09871bed"
    ),
    "urdf/omnihand_left.urdf": (
        "f92d89e4a173e4cf9cbb3bd3edb548d6d14d2da878e07c5d22ec948ba64ae572"
    ),
    "mjcf/omnihand_right.xml": (
        "fca8c46104b25ec55218d95ebe54b9ca670fdf0309c354e854dbc15ac6e939df"
    ),
    "mjcf/omnihand_left.xml": (
        "dfb6ce44e24b17cb775ac3b2f57347a939a27c2b75d6ac99604608bc0aa7608f"
    ),
}


def core_asset_relative_paths() -> List[str]:
    """Return the relative paths of the core runtime assets for both sides."""
    paths: List[str] = []
    for side in SIDES:
        paths.append(URDF_RELATIVE.format(side=side))
        paths.append(MJCF_RELATIVE.format(side=side))
    return paths


def sha256_file(path: Union[str, os.PathLike]) -> str:
    """Return the hex SHA-256 digest of the file at ``path``."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_bytes(data: bytes) -> str:
    """Return the hex SHA-256 digest of an in-memory byte string."""
    return hashlib.sha256(data).hexdigest()


class ProvenanceError(Exception):
    """Raised when provenance verification fails."""


@dataclass(frozen=True)
class ProvenanceManifest:
    """Parsed provenance manifest."""

    upstream_repo: str
    upstream_commit: str
    declared_license: str
    license_confirmed: bool
    # relative_path -> sha256 hex
    files: Mapping[str, str]

    def to_dict(self) -> Dict[str, object]:
        return {
            "upstream_repo": self.upstream_repo,
            "upstream_commit": self.upstream_commit,
            "declared_license": self.declared_license,
            "license_confirmed": self.license_confirmed,
            "files": dict(self.files),
        }


def reference_manifest() -> ProvenanceManifest:
    """Return the reference manifest pinned to the upstream baseline."""
    return ProvenanceManifest(
        upstream_repo=UPSTREAM_REPO,
        upstream_commit=UPSTREAM_COMMIT,
        declared_license=UPSTREAM_DECLARED_LICENSE,
        license_confirmed=UPSTREAM_LICENSE_CONFIRMED,
        files=dict(REFERENCE_HASHES),
    )


def load_manifest(path: Union[str, os.PathLike]) -> ProvenanceManifest:
    """Load a provenance manifest from a JSON file on disk."""
    path = Path(path)
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise ProvenanceError(f"provenance manifest not found: {path}") from error
    except json.JSONDecodeError as error:
        raise ProvenanceError(f"provenance manifest is not valid JSON: {path}") from error
    return parse_manifest(raw)


def parse_manifest(raw: Mapping[str, object]) -> ProvenanceManifest:
    """Parse and structurally validate a provenance manifest mapping."""
    required_keys = ("upstream_repo", "upstream_commit", "declared_license",
                     "license_confirmed", "files")
    missing = [key for key in required_keys if key not in raw]
    if missing:
        raise ProvenanceError(f"provenance manifest missing keys: {missing}")
    files = raw["files"]
    if not isinstance(files, Mapping) or not files:
        raise ProvenanceError("provenance manifest 'files' must be a non-empty mapping")
    normalized: Dict[str, str] = {}
    for rel, digest in files.items():
        if not isinstance(rel, str) or not isinstance(digest, str):
            raise ProvenanceError(
                f"provenance file entry {rel!r} -> {digest!r} must be str -> str"
            )
        normalized[rel] = digest.lower()
    commit = raw["upstream_commit"]
    repo = raw["upstream_repo"]
    if not isinstance(commit, str) or not commit:
        raise ProvenanceError("provenance manifest 'upstream_commit' must be a non-empty string")
    if not isinstance(repo, str) or not repo:
        raise ProvenanceError("provenance manifest 'upstream_repo' must be a non-empty string")
    return ProvenanceManifest(
        upstream_repo=repo,
        upstream_commit=commit,
        declared_license=str(raw["declared_license"]),
        license_confirmed=bool(raw["license_confirmed"]),
        files=normalized,
    )


def _normalize_rel(path: str) -> str:
    return Path(path).as_posix()


def verify_commit(manifest: ProvenanceManifest, *, expect_commit: str = UPSTREAM_COMMIT) -> None:
    """Assert the manifest pins the expected upstream commit."""
    if manifest.upstream_commit.lower() != expect_commit.lower():
        raise ProvenanceError(
            f"upstream commit mismatch: manifest={manifest.upstream_commit!r} "
            f"expected={expect_commit!r}"
        )


def verify_hashes(
    manifest: ProvenanceManifest,
    asset_root: Union[str, os.PathLike],
    *,
    required_files: Iterable[str] = (),
) -> List[str]:
    """Verify every file in the manifest matches its declared SHA-256 on disk.

    Returns the list of verified relative paths. Raises :class:`ProvenanceError`
    on any hash mismatch or missing file. ``required_files`` (defaults to the
    core assets) must all be present in the manifest.
    """
    asset_root = Path(asset_root)
    required = set(_normalize_rel(p) for p in required_files) or set(
        _normalize_rel(p) for p in core_asset_relative_paths()
    )
    declared = {_normalize_rel(p): h for p, h in manifest.files.items()}
    missing_from_manifest = required - set(declared)
    if missing_from_manifest:
        raise ProvenanceError(
            f"manifest is missing required core assets: {sorted(missing_from_manifest)}"
        )

    verified: List[str] = []
    for rel, declared_hash in declared.items():
        asset_path = asset_root / rel
        if not asset_path.is_file():
            raise ProvenanceError(f"declared asset not found on disk: {asset_path}")
        actual = sha256_file(asset_path)
        if actual.lower() != declared_hash.lower():
            raise ProvenanceError(
                f"SHA-256 mismatch for {rel}: declared={declared_hash} actual={actual}"
            )
        verified.append(rel)
    return verified


def build_manifest(
    asset_root: Union[str, os.PathLike],
    *,
    upstream_repo: str = UPSTREAM_REPO,
    upstream_commit: str = UPSTREAM_COMMIT,
    declared_license: str = UPSTREAM_DECLARED_LICENSE,
    license_confirmed: bool = UPSTREAM_LICENSE_CONFIRMED,
    files: Iterable[str] = (),
) -> ProvenanceManifest:
    """Compute a fresh provenance manifest by hashing the assets on disk.

    This is the authoring helper used when assets are (re)generated or vendored.
    The returned manifest is JSON-serializable via :meth:`ProvenanceManifest.to_dict`.
    """
    asset_root = Path(asset_root)
    targets = list(files) or core_asset_relative_paths()
    hashes: Dict[str, str] = {}
    for rel in targets:
        asset_path = asset_root / _normalize_rel(rel)
        if not asset_path.is_file():
            raise ProvenanceError(f"cannot hash missing asset: {asset_path}")
        hashes[_normalize_rel(rel)] = sha256_file(asset_path)
    return ProvenanceManifest(
        upstream_repo=upstream_repo,
        upstream_commit=upstream_commit,
        declared_license=declared_license,
        license_confirmed=license_confirmed,
        files=hashes,
    )


def write_manifest(
    manifest: ProvenanceManifest,
    path: Union[str, os.PathLike],
) -> None:
    """Write a manifest to disk as pretty-printed JSON."""
    Path(path).write_text(
        json.dumps(manifest.to_dict(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
